version: 0.2

phases:
  install:
    runtime-version:
      java: coretto17
  build:
    commands:
      - echo Build started on `date`
      - mvn package
  post-build:
    commands:
      - mv target/CustomerTracker-0.0.1-SNAPSHOT.jar .
artifacts:
  files:
    - CustomerTracker-0.0.1-SNAPSHOT.jar
