version: 0.2

phases:
  install:
    runtime-version:
      java: coretto17
  build:
    commands:
      - echo Build started on `date`
      - mvn package
  post_build:
    commands:
      - mv target/*.jar app.jar
artifacts:
  files:
    - app.jar
