server:
  port: 5000
  servlet:
    context-path: /ctrack
spring:
  application:
    name: Customer Tracker
    mail:
      host: smtp.gmail.com
      port: 600
      username: asdfad
      password: asdfasdf

# example of what it would look like with properties
    # spring.application.mail.host:
    # spring.application.mail.port:
    # spring.application.mail.username:
    # spring.application.mail.password:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://cjester-customer-tracker.ciotsjjufktg.us-east-2.rds.amazonaws.com:5432/postgres
    username: postgres
    password: FloorJava2022!
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true

jwt:
  secret: lookAtMeMrMeeseeks
